# Requires these Apache modules:
# LoadModule proxy_module modules/mod_proxy.so
# LoadModule proxy_http_module modules/mod_proxy_http.so
# LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
# LoadModule ssl_module modules/mod_ssl.so
# LoadModule headers_module modules/mod_headers.so

<VirtualHost *:80>
    ServerName laravel-next-stripe-pdf-demo.local
    Redirect permanent / https://laravel-next-stripe-pdf-demo.local/
</VirtualHost>

<VirtualHost *:443>
    ServerName laravel-next-stripe-pdf-demo.local
    ErrorLog "/absolute/path/to/laravel-next-stripe-pdf-demo.local/logs/ssl-error.log"
    CustomLog "/absolute/path/to/laravel-next-stripe-pdf-demo.local/logs/ssl-access.log" common

    SSLEngine on
    SSLCertificateFile "/absolute/path/to/laravel-next-stripe-pdf-demo.local/web/certificates/localhost.pem"
    SSLCertificateKeyFile "/absolute/path/to/laravel-next-stripe-pdf-demo.local/web/certificates/localhost-key.pem"

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "laravel-next-stripe-pdf-demo.local"

    ProxyPass /_next/webpack-hmr ws://127.0.0.1:3000/_next/webpack-hmr
    ProxyPassReverse /_next/webpack-hmr ws://127.0.0.1:3000/_next/webpack-hmr

    ProxyPass /api/ http://127.0.0.1:8000/api/
    ProxyPassReverse /api/ http://127.0.0.1:8000/api/

    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
